### ISSUE TITLE
AN ERROR OCCURRED

### ISSUE THREAD

**Issue by GiulioCocconi** [clemsciences/runes-analyzer#5]
This is the error
_  File "/Volumes/GIULIO2/Cicada 3301/Rune/runes-analyzer-master/runesanalyzer/runes.py", line 10
SyntaxError: Non-ASCII character '\xc3' in file /Volumes/GIULIO2/Cicada 3301/Rune/runes-analyzer-master/runesanalyzer/runes.py on line 10, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details_

**Comment by clemsciences** [comment]
Hey, I didn't give this precision, but the code uses Python 3.6. So, by default, utf-8 encoding is used.
